import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    pytestSpecSidebar: [
        {
            type: 'autogenerated',
            dirName: 'pytest-spec'
        }
    ],
    tiloSidebar: [
        {
            type: 'autogenerated',
            dirName: 'tilo'
        }
    ],
    darkPrismSidebar: [
        {
            type: 'autogenerated',
            dirName: 'dark-prism'
        }
    ],
};

export default sidebars;
