import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    pytestSpecSidebar: [
        {
            type: 'autogenerated',
            dirName: 'pytest-spec'
        },
        {
            type: 'link',
            label: 'GitHub',
            href: 'https://github.com/pchomik/pytest-spec',
        },
        {
            type: 'link',
            label: 'License',
            href: 'https://raw.githubusercontent.com/pchomik/pytest-spec/refs/heads/master/LICENSE.txt',
        },
    ],
    tiloSidebar: [
        {
            type: 'autogenerated',
            dirName: 'tilo'
        }
    ],
    darkPrismSidebar: [
        {
            type: 'autogenerated',
            dirName: 'dark-prism'
        },
        {
            type: 'link',
            label: 'GitHub',
            href: 'https://github.com/pchomik/dark-prism',
        },
        {
            type: 'link',
            label: 'License',
            href: 'https://raw.githubusercontent.com/pchomik/dark-prism/refs/heads/main/LICENSE',
        },
    ],
};

export default sidebars;
